# coding: utf-8

# flake8: noqa
"""
    Actual Generation

    Generation data aggregated by sector and produced per group (in MW) on an intradaily basis for net generation injected into the network. This data is produced by RTE using remote measurement facilities with which production units are equipped, and using an estimate model for the wind-power and photovoltaic sectors. Hydraulic stocks for France are the aggregated weekly fill rates of reservoirs and lake-type hydraulic storage plants; they are expressed in MWh and sent by the generators to RTE.  # noqa: E501

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from generation_client.models.actual_generations_per_production_type import ActualGenerationsPerProductionType
from generation_client.models.actual_generations_per_production_type_obj import ActualGenerationsPerProductionTypeObj
from generation_client.models.actual_generations_per_unit import ActualGenerationsPerUnit
from generation_client.models.actual_generations_per_unit_obj import ActualGenerationsPerUnitObj
from generation_client.models.error import Error
from generation_client.models.error_error_details import ErrorErrorDetails
from generation_client.models.generation_mix15min_time_scale import GenerationMix15minTimeScale
from generation_client.models.generation_mix15min_time_scale_obj import GenerationMix15minTimeScaleObj
from generation_client.models.unit_actual_generations_per_unit import UnitActualGenerationsPerUnit
from generation_client.models.value_actual_generations_per_production_type import ValueActualGenerationsPerProductionType
from generation_client.models.value_actual_generations_per_unit import ValueActualGenerationsPerUnit
from generation_client.models.value_generation_mix15min_time_scale import ValueGenerationMix15minTimeScale
from generation_client.models.value_water_reserves import ValueWaterReserves
from generation_client.models.water_reserves import WaterReserves
from generation_client.models.water_reserves_obj import WaterReservesObj
