# coding: utf-8

"""
    Actual Generation

    Generation data aggregated by sector and produced per group (in MW) on an intradaily basis for net generation injected into the network. This data is produced by RTE using remote measurement facilities with which production units are equipped, and using an estimate model for the wind-power and photovoltaic sectors. Hydraulic stocks for France are the aggregated weekly fill rates of reservoirs and lake-type hydraulic storage plants; they are expressed in MWh and sent by the generators to RTE.  # noqa: E501

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from generation_client.configuration import Configuration


class Error(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'error': 'str',
        'error_description': 'str',
        'error_uri': 'str',
        'error_details': 'ErrorErrorDetails'
    }

    attribute_map = {
        'error': 'error',
        'error_description': 'error_description',
        'error_uri': 'error_uri',
        'error_details': 'error_details'
    }

    def __init__(self, error=None, error_description=None, error_uri=None, error_details=None, _configuration=None):  # noqa: E501
        """Error - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._error = None
        self._error_description = None
        self._error_uri = None
        self._error_details = None
        self.discriminator = None

        if error is not None:
            self.error = error
        if error_description is not None:
            self.error_description = error_description
        if error_uri is not None:
            self.error_uri = error_uri
        if error_details is not None:
            self.error_details = error_details

    @property
    def error(self):
        """Gets the error of this Error.  # noqa: E501

        short_name, error's explicit description  # noqa: E501

        :return: The error of this Error.  # noqa: E501
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this Error.

        short_name, error's explicit description  # noqa: E501

        :param error: The error of this Error.  # noqa: E501
        :type: str
        """

        self._error = error

    @property
    def error_description(self):
        """Gets the error_description of this Error.  # noqa: E501

        long name, readable by a user  # noqa: E501

        :return: The error_description of this Error.  # noqa: E501
        :rtype: str
        """
        return self._error_description

    @error_description.setter
    def error_description(self, error_description):
        """Sets the error_description of this Error.

        long name, readable by a user  # noqa: E501

        :param error_description: The error_description of this Error.  # noqa: E501
        :type: str
        """

        self._error_description = error_description

    @property
    def error_uri(self):
        """Gets the error_uri of this Error.  # noqa: E501

        URI to the user guide on the VESPA technical platform or the FAQ/documentation on VESPA’s web portal  # noqa: E501

        :return: The error_uri of this Error.  # noqa: E501
        :rtype: str
        """
        return self._error_uri

    @error_uri.setter
    def error_uri(self, error_uri):
        """Sets the error_uri of this Error.

        URI to the user guide on the VESPA technical platform or the FAQ/documentation on VESPA’s web portal  # noqa: E501

        :param error_uri: The error_uri of this Error.  # noqa: E501
        :type: str
        """

        self._error_uri = error_uri

    @property
    def error_details(self):
        """Gets the error_details of this Error.  # noqa: E501


        :return: The error_details of this Error.  # noqa: E501
        :rtype: ErrorErrorDetails
        """
        return self._error_details

    @error_details.setter
    def error_details(self, error_details):
        """Sets the error_details of this Error.


        :param error_details: The error_details of this Error.  # noqa: E501
        :type: ErrorErrorDetails
        """

        self._error_details = error_details

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Error, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Error):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Error):
            return True

        return self.to_dict() != other.to_dict()
