# coding: utf-8

"""
    Actual Generation

    Generation data aggregated by sector and produced per group (in MW) on an intradaily basis for net generation injected into the network. This data is produced by RTE using remote measurement facilities with which production units are equipped, and using an estimate model for the wind-power and photovoltaic sectors. Hydraulic stocks for France are the aggregated weekly fill rates of reservoirs and lake-type hydraulic storage plants; they are expressed in MWh and sent by the generators to RTE.  # noqa: E501

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from generation_client.configuration import Configuration


class GenerationMix15minTimeScale(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'start_date': 'datetime',
        'end_date': 'datetime',
        'production_type': 'str',
        'production_subtype': 'str',
        'values': 'list[ValueGenerationMix15minTimeScale]'
    }

    attribute_map = {
        'start_date': 'start_date',
        'end_date': 'end_date',
        'production_type': 'production_type',
        'production_subtype': 'production_subtype',
        'values': 'values'
    }

    def __init__(self, start_date=None, end_date=None, production_type=None, production_subtype=None, values=None, _configuration=None):  # noqa: E501
        """GenerationMix15minTimeScale - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._start_date = None
        self._end_date = None
        self._production_type = None
        self._production_subtype = None
        self._values = None
        self.discriminator = None

        if start_date is not None:
            self.start_date = start_date
        if end_date is not None:
            self.end_date = end_date
        if production_type is not None:
            self.production_type = production_type
        if production_subtype is not None:
            self.production_subtype = production_subtype
        if values is not None:
            self.values = values

    @property
    def start_date(self):
        """Gets the start_date of this GenerationMix15minTimeScale.  # noqa: E501

        Search start date (YYYY-MM-DDThh:mm:sszzzzzz)  # noqa: E501

        :return: The start_date of this GenerationMix15minTimeScale.  # noqa: E501
        :rtype: datetime
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """Sets the start_date of this GenerationMix15minTimeScale.

        Search start date (YYYY-MM-DDThh:mm:sszzzzzz)  # noqa: E501

        :param start_date: The start_date of this GenerationMix15minTimeScale.  # noqa: E501
        :type: datetime
        """

        self._start_date = start_date

    @property
    def end_date(self):
        """Gets the end_date of this GenerationMix15minTimeScale.  # noqa: E501

        Search end date (YYYY-MM-DDThh:mm:sszzzzzz)  # noqa: E501

        :return: The end_date of this GenerationMix15minTimeScale.  # noqa: E501
        :rtype: datetime
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """Sets the end_date of this GenerationMix15minTimeScale.

        Search end date (YYYY-MM-DDThh:mm:sszzzzzz)  # noqa: E501

        :param end_date: The end_date of this GenerationMix15minTimeScale.  # noqa: E501
        :type: datetime
        """

        self._end_date = end_date

    @property
    def production_type(self):
        """Gets the production_type of this GenerationMix15minTimeScale.  # noqa: E501

        Generating sector  # noqa: E501

        :return: The production_type of this GenerationMix15minTimeScale.  # noqa: E501
        :rtype: str
        """
        return self._production_type

    @production_type.setter
    def production_type(self, production_type):
        """Sets the production_type of this GenerationMix15minTimeScale.

        Generating sector  # noqa: E501

        :param production_type: The production_type of this GenerationMix15minTimeScale.  # noqa: E501
        :type: str
        """
        allowed_values = ["FOSSIL_OIL", "FOSSIL_GAS", "HYDRO", "BIOENERGY", "NUCLEAR", "FOSSIL_HARD_COAL", "WIND", "EXCHANGE", "PUMPING", "SOLAR"]  # noqa: E501
        if (self._configuration.client_side_validation and
                production_type not in allowed_values):
            raise ValueError(
                "Invalid value for `production_type` ({0}), must be one of {1}"  # noqa: E501
                .format(production_type, allowed_values)
            )

        self._production_type = production_type

    @property
    def production_subtype(self):
        """Gets the production_subtype of this GenerationMix15minTimeScale.  # noqa: E501

        Generating sub-sector  # noqa: E501

        :return: The production_subtype of this GenerationMix15minTimeScale.  # noqa: E501
        :rtype: str
        """
        return self._production_subtype

    @production_subtype.setter
    def production_subtype(self, production_subtype):
        """Sets the production_subtype of this GenerationMix15minTimeScale.

        Generating sub-sector  # noqa: E501

        :param production_subtype: The production_subtype of this GenerationMix15minTimeScale.  # noqa: E501
        :type: str
        """
        allowed_values = ["TOTAL", "FOSSIL_OIL_OTHER", "FOSSIL_OIL_CHP", "FOSSIL_OIL_CT", "FOSSIL_GAS_OTHER", "FOSSIL_GAS_CCGT", "FOSSIL_GAS_CHP", "FOSSIL_GAS_CT", "HYDRO_PUMPED_STORAGE", "HYDRO_WATER_RESERVOIR", "HYDRO_RUN_OF_RIVER_AND_POUNDAGE", "BIOGAS", "BIOMASS", "WASTE"]  # noqa: E501
        if (self._configuration.client_side_validation and
                production_subtype not in allowed_values):
            raise ValueError(
                "Invalid value for `production_subtype` ({0}), must be one of {1}"  # noqa: E501
                .format(production_subtype, allowed_values)
            )

        self._production_subtype = production_subtype

    @property
    def values(self):
        """Gets the values of this GenerationMix15minTimeScale.  # noqa: E501


        :return: The values of this GenerationMix15minTimeScale.  # noqa: E501
        :rtype: list[ValueGenerationMix15minTimeScale]
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this GenerationMix15minTimeScale.


        :param values: The values of this GenerationMix15minTimeScale.  # noqa: E501
        :type: list[ValueGenerationMix15minTimeScale]
        """

        self._values = values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GenerationMix15minTimeScale, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GenerationMix15minTimeScale):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GenerationMix15minTimeScale):
            return True

        return self.to_dict() != other.to_dict()
