# coding: utf-8

"""
    Actual Generation

    Generation data aggregated by sector and produced per group (in MW) on an intradaily basis for net generation injected into the network. This data is produced by RTE using remote measurement facilities with which production units are equipped, and using an estimate model for the wind-power and photovoltaic sectors. Hydraulic stocks for France are the aggregated weekly fill rates of reservoirs and lake-type hydraulic storage plants; they are expressed in MWh and sent by the generators to RTE.  # noqa: E501

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import generation_client
from generation_client.api.default_api import DefaultApi  # noqa: E501
from generation_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = generation_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_001(self):
        """Test case for 001

        """
        pass

    def test_002(self):
        """Test case for 002

        """
        pass

    def test_003(self):
        """Test case for 003

        """
        pass

    def test_004(self):
        """Test case for 004

        """
        pass


if __name__ == '__main__':
    unittest.main()
